# Generated by Django 6.0.6 on 2026-06-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('jobseeker', 'Job Seeker'), ('recruiter', 'Recruiter')], default='jobseeker', max_length=20),
        ),
    ]
